### ISSUE TITLE
Include parameterizations for zennit xai computations.

### ISSUE THREAD

**Issue by leanderweber** [understandable-machine-intelligence-lab/Quantus#56]
At the moment, the zennit wrapper only uses default parameterizations. The user should be able to pass parameters to canonizer, composite, and attributor as kwargs.

**Comment by annahedstroem** [comment]
fixed in https://github.com/understandable-machine-intelligence-lab/Quantus/pulls

**Comment by leanderweber** [comment]
not yet fixed. Zennit offers a bit more parameterisation options than the wrapper currently does. Would be nice to be able to pass those.

**Comment by dkrako** [comment]
I'll second this and I would need that feature not just for zennit, but for captum, too.

I think for a complete parametrisation of both frameworks we would need to pass two kinds of kwargs:
* `kwargs` for the `__init__` constructor method (e.g. `IntegratedGradients`)
* `kwargs` for the `__call__` calling method of the explanation object (e.g. `IntegratedGradients().attribute()`)

Just passing down the kwargs from the original Metric constructor (e.g. `RegionPerturbation`) or its call-method won't work, as those packages will throw an error if they get unexpected arguments.

I would therefore propose the following:

Add two arguments to the metric `__init__` and `__call__` methods:
* `explain_init_kwargs`: this will hold the kwargs passed to the attribution class constructor (e.g. `IntegratedGradients(**explain_init_kwargs)`)
* `explain_call_kwargs`: this will hold the kwargs passed to the attribute method of the attributor object (e.g. `IntegratedGradients().attribute(**explain_call_kwargs)` )

All in all an example call would then look like this:
`IntegratedGradients(**explain_init_kwargs).attribute(inputs, targets, **explain_call_kwargs)`

I think this will be the cleanest solution for the issue.

**Comment by dkrako** [comment]
Actually thinking more about this, the explanation functions should be reimplemented as classes. Otherwise, we would need even more arguments for zennit canonizer and composite (e.g. `explain_canonizer_kwargs`,  `explain_composite_kwargs`). This would then be dragged through all the metrics and will create unnecessary bloat. If a new XAI-package will be integrated, even more arguments could be introduced. All in all, these are symptoms of an anti-pattern.

Instead, a good architectural choice could be to create classes which implement an interface or abstract class (e.g. `ExplainerInterface`) with methods every inheriting `ExplainerClass` will have to implement. We could even create an intermediate abstract class like `ZennitExplainer` which will have some kind of keyword-arguments like these proposed yesterday.

Before or on calling the metrics, such an `ExplainerClass` will have to be instantiated, but all the bloat will then be completely separated from the metrics.
